// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CcProjectColumns holds the columns for the "cc_project" table.
	CcProjectColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期", SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "Update Time | 修改日期", SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "create_by", Type: field.TypeString, Comment: "创建人"},
		{Name: "update_by", Type: field.TypeString, Nullable: true, Comment: "修改人"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "Delete Time | 删除日期", SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "name", Type: field.TypeString, Comment: "项目名称"},
		{Name: "code", Type: field.TypeString, Comment: "项目编码"},
	}
	// CcProjectTable holds the schema information for the "cc_project" table.
	CcProjectTable = &schema.Table{
		Name:       "cc_project",
		Columns:    CcProjectColumns,
		PrimaryKey: []*schema.Column{CcProjectColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CcProjectTable,
	}
)

func init() {
	CcProjectTable.Annotation = &entsql.Annotation{
		Table: "cc_project",
	}
}
