// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CcProjectColumns holds the columns for the "cc_project" table.
	CcProjectColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true, Comment: "主键"},
		{Name: "name", Type: field.TypeString, Comment: "项目名称"},
		{Name: "code", Type: field.TypeString, Comment: "项目编码"},
		{Name: "create_by", Type: field.TypeUint64, Nullable: true, Comment: "创建人"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_by", Type: field.TypeUint64, Nullable: true, Comment: "更新人"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "tenant_id", Type: field.TypeUint64, Nullable: true, Comment: "租户号"},
		{Name: "deleted", Type: field.TypeBool, Comment: "是否删除"},
	}
	// CcProjectTable holds the schema information for the "cc_project" table.
	CcProjectTable = &schema.Table{
		Name:       "cc_project",
		Columns:    CcProjectColumns,
		PrimaryKey: []*schema.Column{CcProjectColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CcProjectTable,
	}
)

func init() {
	CcProjectTable.Annotation = &entsql.Annotation{
		Table: "cc_project",
	}
}
