// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilName(value *string) *ProjectUpdate {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilName(value *string) *ProjectUpdateOne {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilName(value *string) *ProjectCreate {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilCode(value *string) *ProjectUpdate {
	if value != nil {
		return pr.SetCode(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilCode(value *string) *ProjectUpdateOne {
	if value != nil {
		return pr.SetCode(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilCode(value *string) *ProjectCreate {
	if value != nil {
		return pr.SetCode(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilCreateBy(value *uint64) *ProjectUpdate {
	if value != nil {
		return pr.SetCreateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilCreateBy(value *uint64) *ProjectUpdateOne {
	if value != nil {
		return pr.SetCreateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilCreateBy(value *uint64) *ProjectCreate {
	if value != nil {
		return pr.SetCreateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilCreateTime(value *time.Time) *ProjectUpdate {
	if value != nil {
		return pr.SetCreateTime(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilCreateTime(value *time.Time) *ProjectUpdateOne {
	if value != nil {
		return pr.SetCreateTime(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilCreateTime(value *time.Time) *ProjectCreate {
	if value != nil {
		return pr.SetCreateTime(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilUpdateBy(value *uint64) *ProjectUpdate {
	if value != nil {
		return pr.SetUpdateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilUpdateBy(value *uint64) *ProjectUpdateOne {
	if value != nil {
		return pr.SetUpdateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilUpdateBy(value *uint64) *ProjectCreate {
	if value != nil {
		return pr.SetUpdateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilUpdateTime(value *time.Time) *ProjectUpdate {
	if value != nil {
		return pr.SetUpdateTime(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilUpdateTime(value *time.Time) *ProjectUpdateOne {
	if value != nil {
		return pr.SetUpdateTime(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilUpdateTime(value *time.Time) *ProjectCreate {
	if value != nil {
		return pr.SetUpdateTime(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilTenantID(value *uint64) *ProjectUpdate {
	if value != nil {
		return pr.SetTenantID(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilTenantID(value *uint64) *ProjectUpdateOne {
	if value != nil {
		return pr.SetTenantID(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilTenantID(value *uint64) *ProjectCreate {
	if value != nil {
		return pr.SetTenantID(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilDeleted(value *bool) *ProjectUpdate {
	if value != nil {
		return pr.SetDeleted(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilDeleted(value *bool) *ProjectUpdateOne {
	if value != nil {
		return pr.SetDeleted(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilDeleted(value *bool) *ProjectCreate {
	if value != nil {
		return pr.SetDeleted(*value)
	}
	return pr
}
