// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilUpdatedAt(value *time.Time) *ProjectUpdate {
	if value != nil {
		return pr.SetUpdatedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilUpdatedAt(value *time.Time) *ProjectUpdateOne {
	if value != nil {
		return pr.SetUpdatedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilUpdatedAt(value *time.Time) *ProjectCreate {
	if value != nil {
		return pr.SetUpdatedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilUpdateBy(value *string) *ProjectUpdate {
	if value != nil {
		return pr.SetUpdateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilUpdateBy(value *string) *ProjectUpdateOne {
	if value != nil {
		return pr.SetUpdateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilUpdateBy(value *string) *ProjectCreate {
	if value != nil {
		return pr.SetUpdateBy(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilDeletedAt(value *time.Time) *ProjectUpdate {
	if value != nil {
		return pr.SetDeletedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilDeletedAt(value *time.Time) *ProjectUpdateOne {
	if value != nil {
		return pr.SetDeletedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilDeletedAt(value *time.Time) *ProjectCreate {
	if value != nil {
		return pr.SetDeletedAt(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilName(value *string) *ProjectUpdate {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilName(value *string) *ProjectUpdateOne {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilName(value *string) *ProjectCreate {
	if value != nil {
		return pr.SetName(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdate) SetNotNilCode(value *string) *ProjectUpdate {
	if value != nil {
		return pr.SetCode(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectUpdateOne) SetNotNilCode(value *string) *ProjectUpdateOne {
	if value != nil {
		return pr.SetCode(*value)
	}
	return pr
}

// set field if value's pointer is not nil.
func (pr *ProjectCreate) SetNotNilCode(value *string) *ProjectCreate {
	if value != nil {
		return pr.SetCode(*value)
	}
	return pr
}
